name: Test Ubicloud Prod Runners

on:
  push:
    branches: [check-dns]
 
jobs:
  test:
    strategy:
      # max-parallel: 1
      matrix:
        runs-on: [ubicloud]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: resolvectl status
        run: resolvectl status

      - name: nslookup api.momence.com
        run: nslookup api.momence.com
        continue-on-error: true

      - name: change DNS provider from Quad9 to Cloudflare
        run: |
          echo "[Resolve]
          DNS=1.1.1.1 2606:4700:4700::1111" | sudo tee /etc/systemd/resolved.conf.d/Ubicloud.conf
          sudo systemctl restart systemd-resolved.service

      - name: resolvectl status
        run: resolvectl status

      - name: nslookup api.momence.com
        run: nslookup api.momence.com
 
        

