name: Test Ubicloud Prod Runners

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  test:
    # container:
    #   image: ubuntu:latest
      # options: --init
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubicloud-standard-2-ubuntu-2604
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-2-ubuntu-2204
          - ubuntu-2204
          - ubuntu-2404
          - ubuntu-2604

    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.runs-on }}
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - run: uptime -s
      - name: check kernel
        run: uname -a
      - run: lsb_release -a
